export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/'
export const REGISTRATION_ROUTE = '/registration'
export const FORM_ROUTE = '/form'
export const MENU_ROUTE = '/main_page'
export const EXIT_ROUTE = '/exit'
export const REGIONS_ROUTE = '/regions'